### ISSUE TITLE
data range problem

### ISSUE THREAD

**Issue by hydr0boy** [NMBGMR/wellpy#13]
So I came across a problem today, and I believe it stems from having one random manual WL measurement for the well that dates back to the '50s. I've attached the error code.  

I really don't want to even have to see that data point but I might as well just use my zoom feature to ignore it once we figure out how to get it into the program? 
![old data error](https://user-images.githubusercontent.com/29488408/34800134-bd5e26f0-f61f-11e7-888b-04c7bf37a143.png)

**Comment by jirhiker** [comment]
Added a temporary fix. Pre 1970 points will default to 1/1/1970

What site has this old date?
