### ISSUE TITLE
Not connecting To the Data base

### ISSUE THREAD

**Issue by hydr0boy** [NMBGMR/wellpy#19]
Kitty told me they've been messing with the database. Something about removing the 'time' thing they'd added to the 'Date/Time' field. Regardless, seems like it killed the connection to the DB. No real rush, I'm going to be gone the rest of the week.

![image](https://user-images.githubusercontent.com/29488408/35652829-93f5f552-06a2-11e8-96dc-1006af432ecb.png)

**Comment by jirhiker** [comment]
OK. But nothing abnormal about that launch you included
